theme: jekyll-theme-modernist
title: Association of McGill Professors of Science/Association McGillienne de Professeur.e.s de Sciences
description: A minimalist public-facing AMPS website/Un site Web AMPS minimaliste destiné au public
